BMSS.WebUI/Controllers/CashSalesCreditController.cs
using AutoMapper;
using BMSS.Domain;
using BMSS.Domain.Abstract;
using BMSS.Domain.Abstract.SAP;
using BMSS.Domain.Entities;
using BMSS.WebUI.Helpers.Attributes;
using BMSS.WebUI.Models.CashSalesCreditViewModels;
using BMSS.WebUI.Models.General;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace BMSS.WebUI.Controllers
{
    [Authorize(Roles = "Cash Sales Credit Note")]
    public class CashSalesCreditController : Controller
    {
        private I_CashSalesCreditDocH_Repository i_CashSalesCreditDocH_Repository;
        private I_CashSalesCreditDocLs_Repository i_CashSalesCreditDocLs_Repository;
        private I_OCRD_Repository i_OCRD_Repository;
        private I_OSLP_Repository i_OSLP_Repository;
        private I_OACT_Repository i_OACT_Repository;
        private I_CashSalesCustomer_Repository i_CashSalesCustomer_Repository;
        private I_OITM_Repository i_OITM_Repository;
        IMapper _mapper;
        public CashSalesCreditController(I_OITM_Repository i_OITM_Repository, I_CashSalesCustomer_Repository i_CashSalesCustomer_Repository, I_OSLP_Repository i_OSLP_Repository, I_OACT_Repository i_OACT_Repository, I_OCRD_Repository i_OCRD_Repository, I_CashSalesCreditDocLs_Repository i_CashSalesCreditDocLs_Repository, I_CashSalesCreditDocH_Repository i_CashSalesCreditDocH_Repository, I_OCTG_Repository i_OCTG_Repository, IMapper _mapper)
        {
            this.i_CashSalesCreditDocH_Repository = i_CashSalesCreditDocH_Repository;
            this.i_OCRD_Repository = i_OCRD_Repository;
            this.i_OACT_Repository = i_OACT_Repository;
            this.i_OSLP_Repository = i_OSLP_Repository;
            this.i_CashSalesCreditDocLs_Repository = i_CashSalesCreditDocLs_Repository;
            this.i_CashSalesCustomer_Repository = i_CashSalesCustomer_Repository;
            this.i_OITM_Repository = i_OITM_Repository;
            this._mapper = _mapper;
        }
        public ActionResult Index()
        {
            return View(i_CashSalesCreditDocH_Repository.CashSalesCreditHeaderList);
        }
        [HttpPost]
        [AjaxOnly]
        public JsonResult CanPrint(string DocEntry)
        {
            if (CannotPrintAndSave(DocEntry))
            {
                var DOObj = new { canAccess = false };
                return Json(DOObj, JsonRequestBehavior.DenyGet);
            }
            else
            {
                var DOObj = new { canAccess = true };
                return Json(DOObj, JsonRequestBehavior.DenyGet);
            }

        }
        private Boolean CannotPrintAndSave(string DocEntry)
        {
            CashSalesCreditDocH CashSalesCreditHeader = i_CashSalesCreditDocH_Repository.GetByDocEntry(DocEntry);
            return CashSalesCreditHeader.PrintedCount >= 1 && !User.IsInRole("Print After First Time");

        }
        public ActionResult Edit(string DocNum)
        {

            var ResultObject = i_OACT_Repository.GLCodes.FirstOrDefault(x => x.AcctName.Equals("Cash at Bank - OCBC"));
            string defaultGLCode = string.Empty;
            if (ResultObject != null)
                defaultGLCode = ResultObject.AcctCode;

            ViewBag.defaultGLCode = defaultGLCode;

            CashSalesCreditViewModel addCashSalesCreditViewModel = new CashSalesCreditViewModel();

            CashSalesCreditDocH CashSalesHObject = i_CashSalesCreditDocH_Repository.GetByDocNumber(DocNum);

            if (CashSalesHObject != null)
            {
                addCashSalesCreditViewModel = _mapper.Map<CashSalesCreditDocH, CashSalesCreditViewModel>(CashSalesHObject);
                addCashSalesCreditViewModel.CardName = addCashSalesCreditViewModel.CardCode;
                addCashSalesCreditViewModel.Lines = new List<CashSalesCreditLineViewModel>();
                addCashSalesCreditViewModel.NoteLines = new List<CashSalesCreditNoteViewModel>();
                addCashSalesCreditViewModel.PayLines = new List<CashSalesCreditPayViewModel>();

                foreach (var entry in CashSalesHObject.CashSalesCreditDocLs.OrderBy(x => x.LineNum))
                {
                    CashSalesCreditLineViewModel dOLine = new CashSalesCreditLineViewModel();
                    dOLine = _mapper.Map<CashSalesCreditDocLs, CashSalesCreditLineViewModel>(entry);
                    addCashSalesCreditViewModel.Lines.Add(dOLine);
                }
                if (CashSalesHObject.CashSalesCreditDocNotes != null)
                {
                    foreach (var entry in CashSalesHObject.CashSalesCreditDocNotes.OrderBy(x => x.LineNum))
                    {
                        CashSalesCreditNoteViewModel dONoteLine = new CashSalesCreditNoteViewModel();
                        dONoteLine = _mapper.Map<CashSalesCreditDocNotes, CashSalesCreditNoteViewModel>(entry);
                        addCashSalesCreditViewModel.NoteLines.Add(dONoteLine);
                    }
                }
                if (CashSalesHObject.CashSalesCreditDocPays != null)
                {
                    foreach (var entry in CashSalesHObject.CashSalesCreditDocPays.OrderBy(x => x.LineNum))
                    {
                        CashSalesCreditPayViewModel dOPayLine = new CashSalesCreditPayViewModel();
                        dOPayLine = _mapper.Map<CashSalesCreditDocPays, CashSalesCreditPayViewModel>(entry);
                        addCashSalesCreditViewModel.PayLines.Add(dOPayLine);
                    }
                }
                addCashSalesCreditViewModel.DocDate = CashSalesHObject.DocDate.ToString("dd'/'MM'/'yyyy");
                //addCashSalesCreditViewModel.DeliveryDate = CashSalesHObject.DeliveryDate.ToString("dd'/'MM'/'yyyy");
                //addCashSalesCreditViewModel.DueDate = CashSalesHObject.DueDate.ToString("dd'/'MM'/'yyyy");
                addCashSalesCreditViewModel.DiscByPercent = addCashSalesCreditViewModel.DiscByPercent.ToLower();

            }
            else
            {
                TempData["GlobalErrMsg"] = "Sales quotation not found";
                return RedirectToAction("Index");
            }

            return View("Add", addCashSalesCreditViewModel);
        }

        public ActionResult Add()
        {
            //var ResultCustomerObject = i_OCRD_Repository.GetCustomerDetails("CASH-SALE");

            var ResultObject = i_OACT_Repository.GLCodes.FirstOrDefault(x => x.AcctName.Equals("Cash at Bank - OCBC"));
            string defaultGLCode = string.Empty;
            if (ResultObject != null)
                defaultGLCode = ResultObject.AcctCode;

            ViewBag.defaultGLCode = defaultGLCode;

            CashSalesCreditViewModel addCashSalesCreditViewModel = new CashSalesCreditViewModel()
            {
                DocDate = DateTime.Now.ToString("dd'/'MM'/'yyyy"),
                //DeliveryDate = DateTime.Now.ToString("dd'/'MM'/'yyyy"),
                //DueDate = DateTime.Now.AddDays(ResultCustomerObject.PaymentTerm.ExtraDays).ToString("dd/MM/yyyy"),
                DocNum = "New",
                DiscByPercent = "true",
                DiscAmount = 0,
                DiscPercent = 0,
                SubmittedToSAP = false,
                //Currency = ResultCustomerObject.Currency,
                //CardCode = ResultCustomerObject.CardCode,
                //CardName = ResultCustomerObject.CardName,
                //PaymentTermName = ResultCustomerObject.PaymentTerm.PymntGroup,
                //SlpName = ResultCustomerObject.SalesPerson.SlpName,
            };
            return View(addCashSalesCreditViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken()]
        [AjaxOnly]
        [EditAuthorize(Roles = "Cash Sales Credit Note-Edit")]
        public JsonResult Add(CashSalesCreditViewModel CashSalesObj)
        {
            CashSalesObj.CashSalesCardName = "-";
            CashSalesObj.BillTo = "-";
            IEnumerable<string> ModelErrList = Enumerable.Empty<string>();
            List<string> ErrList = new List<string>();
            if (CashSalesObj.Lines == null || CashSalesObj.Lines.Count() <= 0)
            {
                ErrList.Add("No lines added");

            }
            else if (CashSalesObj.PayLines == null || CashSalesObj.PayLines.Count() <= 0)
            {
                ErrList.Add("No Pay lines added");
            }
            else if (CashSalesObj.GrandTotal > (CashSalesObj.PayLines.Sum(x => x.PaidAmount)))
            {
                ErrList.Add("Paid Amount lesser than Grand Total");
            }
            else if (CashSalesObj.GrandTotal < (CashSalesObj.PayLines.Sum(x => x.PaidAmount)))
            {
                ErrList.Add("Paid Amount greater than Grand Total");
            }
            for (int i = 0; i < CashSalesObj.Lines.Count(); i++)
            {
                OITM ItemDetails = i_OITM_Repository.GetItemDetails(CashSalesObj.Lines[i].ItemCode);
                string isUnitCostRequired = ItemDetails.U_ALLOW_UNIT_COST_ZERO;
                if (isUnitCostRequired != null && isUnitCostRequired == "N")
                {
                    if (CashSalesObj.Lines[i].UnitCost <= 0)
                        ErrList.Add("For item " + CashSalesObj.Lines[i].ItemCode + ", Unit Cost should be greater than zero in line no " + (i + 1));
                }

            }
            if (ModelState.IsValid && ErrList.Count() <= 0)
            {
                if (CashSalesObj.DocNum.Equals("New"))
                {
                    CashSalesCreditDocH CashSalesCreditHeader = new CashSalesCreditDocH();
                    CashSalesCreditHeader = _mapper.Map<CashSalesCreditViewModel, CashSalesCreditDocH>(CashSalesObj);
                    var ResultCustomerObject = i_OCRD_Repository.GetCustomerDetails(CashSalesCreditHeader.CardCode);
                    //var CashCustomerObject = i_CashSalesCustomer_Repository.GetByTelephoneNo(CashSalesCreditHeader.OfficeTelNo);
                    

BMSS.WebUI/Views/CashSalesCredit/Index.cshtml
@using BMSS.Domain
@model IEnumerable<CashSalesCreditDocH>
@using System.Globalization;
@{
    ViewBag.Title = "List of Cash Sales Credit";
}
@section Styles {
    @Styles.Render("~/DataTablesCss")
}
@section Content_Header {
    <section class="content-header">
        <h1>
            Cash Sale Credit Note Listing
            <small>Cash Sales Credit Note</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href='@Url.Action("Index", "Home")'><i class="fa fa-dashboard"></i>Transactions</a></li>
            <li class="active">Cash Sales Credit Note</li>
        </ol>
    </section>
}
<div class="row">
    <div class="col-12">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">List of Cash Sales Credit Note</h3>
                <div class="box-tools" style="top: 3px;"><a class="btn btn-primary" href="@Url.Action("Add", "CashSalesCredit")" role="button">Add</a></div>
            </div>
            <div class="box-body">
                <table id="DeliveryOrderList" class="table table-bordered table-striped responsive nowrap bmdatatable dblEdit" data-fixed-header="true" data-auto-width="true" data-paging="true" data-searching="true" data-length-change="true" data-page-length="100" data-ordering="true" style="width:100%">
                    <thead>
                        <tr>
                            <th>Doc #</th>
                            <th>Date</th>
                            <th>Account #</th>

                            <th class="text-right">Amount</th>

                            <th>Print Status</th>
                            <th>SAP Status</th>
                            <th>SRI #</th>
                            <td data-priority="1">Print</td>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int rowid = 0;
                            
                        }
                        @foreach (var i in Model)
                        {
                            string sRemarks = "";
                            if (i.SubmittedBy != null)
                            {
                                sRemarks = i.SubmittedBy != null ? $"{i.SyncRemarks}, Submitted by {i.SubmittedBy}, Submitted on {i.SubmittedOn?.ToString("dd'/'MM'/'yyyy hh:mm:ss")}" : i.SyncRemarks;
                            }
                           
                            <tr data-toggle="tooltip" title="double click to edit">
                                <td>
                                    @i.DocNum
                                    @using (Html.BeginForm("Edit", null, null, FormMethod.Get, new { id = "DetailForm" }))
                                    {
                                        @Html.Hidden("DocNum", @i.DocNum)
                                    }
                                </td>
                                <td>@i.DocDate.ToString("dd'/'MM'/'yyyy")</td>
                                <td>@i.CardCode</td>

                                <td class="text-right">@i.GrandTotal.ToString("N2", new CultureInfo("en-US"))</td>

                                <td>@Html.GetPrintedStatusName(i.PrintedStatus)</td>
                                <td>
                                    @Html.GetSyncStatusName(i.SyncStatus)
                                    @if (i.SyncStatus > 1)
                                    {
                                        <span data-toggle='popover' data-trigger='hover' data-placement='right' data-html='true' data-content='@sRemarks' data-title='Sync Remarks'><i class='fa fa-fw fa-info-circle'></i></span>
                                    }
                                </td>
                                <td>@i.SRINo</td>
                                <td data-priority="1"><a class="btn btn-primary btn-xs printPreview" data-row-docnum="@i.DocEntry" data-row-index="@rowid" target="_blank" href="@Url.Action("CSCViewer.aspx","WForms/", new { id = i.DocEntry})" role="button">Print</a></td>

                            </tr>
                            rowid = rowid + 1;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/DataTables")
    @Scripts.Render("~/Own")
    <script>       
            $(document).on('click', '.printPreview', function (e) {
            e.preventDefault();
            let rowNo = $(this).data('row-index');
            let DocEntry = $(this).data('row-docnum');
            let URL = $(this).attr("href");             
            $.ajax({
                url: "@Url.Action("CanPrint", "CashSalesCredit", null)",
                type: 'post',
                contentType: 'application/x-www-form-urlencoded',
                data: { DocEntry: DocEntry },
                success: function (data)
                {
                    if (data.canAccess) {
                       
                        let DeliveryOrderList = $('#DeliveryOrderList').DataTable();
                               
                        let temp = DeliveryOrderList.row(rowNo).data();
                        temp[4] = "Printed";
                        DeliveryOrderList.row(rowNo).data(temp).invalidate();
                        window.open(URL, '_blank');
                               
                    }
                    else {
                        window.scrollTo({ top: 0, behavior: 'smooth' });
                        $('<div class="alert alert-danger alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><h4><i class="icon fa fa-ban"></i> Alert!</h4><p>Access denied</p></div>')
                            .prependTo($('.box-body'))
                            .delay(5000)
                            .slideUpAndRemove('slow');   
                    }
                            
                },
                error: function ()
                {
                             
                }
            });
        });
    </script>
}