BMSS.WebUI/Models/StockTransViewModels/StockTransViewModel.cs
using BMSS.WebUI.Helpers.Attributes.Validation;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BMSS.WebUI.Models.StockTransViewModels
{
    public class StockTransViewModel
    {
        public long DocEntry { get; set; }
        public bool IsModelValid { get; set; } = true;
        public List<string> ModelErrList { get; set; }

        [JsonProperty(PropertyName = "docNum")]
        [Display(Name = "Doc No")]
        [MaxLength(50)]
        public string DocNum { get; set; }

        [JsonProperty(PropertyName = "docDate")]
        [Display(Name = "Doc Date")]
        [Required]
        [ValidDateFormat(ErrorMessageResourceName = "Doc Date",DateFormat = "dd'/'MM'/'yyyy",ErrorMessage ="field is invalid", ShouldGTEToday = true)]
        public string DocDate { get; set; }

        [JsonProperty(PropertyName = "status")]
        [Display(Name = "Status")]
        public short Status { get; set; }
        [JsonProperty(PropertyName = "printedStatus")]
        [Display(Name = "Printed Status")]
         
        public short PrintedStatus { get; set; }
        [JsonProperty(PropertyName = "syncStatus")]
        [Display(Name = "Sync Status")]
        [ReadOnly(true)]
        public short SyncStatus { get; set; }
        [JsonProperty(PropertyName = "ref")]
        [Display(Name = "Ref")]
        [MaxLength(100)]
        public string Ref { get; set; }
        [JsonProperty(PropertyName = "createdOn")]
        [Display(Name = "Created On")]
        [ReadOnly(true)]
        public DateTime CreatedOn { get; set; }

        [JsonProperty(PropertyName = "createdBy")]
        [Display(Name = "Created By")]
        [ReadOnly(true)]
        public string CreatedBy { get; set; }

        [JsonProperty(PropertyName = "updatedBy")]
        [Display(Name = "Last Updated By")]
        [ReadOnly(true)]
        public string UpdatedBy { get; set; }
        [ReadOnly(true)]
        [JsonProperty(PropertyName = "updatedOn")]
        [Display(Name = "Last Updated On")]
        public DateTime UpdatedOn { get; set; }

        [JsonProperty(PropertyName = "submittedToSAP")]
        public bool SubmittedToSAP { get; set; }
        [JsonProperty(PropertyName = "syncedToSAP")]
        public bool SyncedToSAP { get; set; }
        [JsonProperty(PropertyName = "lines")]
        public List<StockTransLineViewModel> Lines { get; set; }
        [JsonProperty(PropertyName = "noteLines")]
        public List<StockTransNoteViewModel> NoteLines { get; set; }
    }
}

BMSS.WebUI/Controllers/StockTransController.cs
using AutoMapper;
using BMSS.Domain;
using BMSS.Domain.Abstract;
using BMSS.Domain.Abstract.SAP;
using BMSS.Domain.Entities;
using BMSS.WebUI.Helpers.Attributes;
using BMSS.WebUI.Models.General;
using BMSS.WebUI.Models.StockTransViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace BMSS.WebUI.Controllers
{
    [Authorize(Roles = "Stock Transfer")]
  
    public class StockTransController : Controller
    {
        private I_StockTransDocH_Repository i_StockTransDocH_Repository;
        private I_StockTransDocLs_Repository i_StockTransDocLs_Repository;
        private I_DODocH_Repository i_DODocH_Repository;
        private I_OITW_Repository i_OITW_Repository;
        IMapper _mapper;
        public StockTransController(I_OITW_Repository i_OITW_Repository, I_DODocH_Repository i_DODocH_Repository, I_StockTransDocLs_Repository i_StockTransDocLs_Repository, I_StockTransDocH_Repository i_StockTransDocH_Repository, IMapper _mapper)
        {
            this.i_StockTransDocH_Repository = i_StockTransDocH_Repository;
            this.i_StockTransDocLs_Repository = i_StockTransDocLs_Repository;
            this.i_DODocH_Repository = i_DODocH_Repository;
            this.i_OITW_Repository = i_OITW_Repository;
            this._mapper = _mapper;
        }
        public ActionResult Index()
        {
            return View(i_StockTransDocH_Repository.StockTransHeaderList);
        }
        [HttpPost]
        [AjaxOnly]
        public JsonResult CanPrint(string DocEntry)
        {
            if (CannotPrintAndSave(DocEntry))
            {
                var DOObj = new { canAccess = false };
                return Json(DOObj, JsonRequestBehavior.DenyGet);
            }
            else
            {
                var DOObj = new { canAccess = true };
                return Json(DOObj, JsonRequestBehavior.DenyGet);
            }

        }
        private Boolean CannotPrintAndSave(string DocEntry)
        {
            StockTransDocH StockTransDocHeader = i_StockTransDocH_Repository.GetByDocEntry(DocEntry);
            return StockTransDocHeader.PrintedCount >= 1 && !User.IsInRole("Print After First Time");

        }
        public ActionResult Add()
        {
            StockTransViewModel addStockTransViewModel = new StockTransViewModel()
            {
                DocDate = DateTime.Now.ToString("dd'/'MM'/'yyyy"),
                DocNum = "New",
                SubmittedToSAP = false,

            };
            return View(addStockTransViewModel);
        }
        public ActionResult Edit(string DocNum)
        {
            StockTransViewModel addStockTransViewModel = new StockTransViewModel();

            StockTransDocH StockTransHObject = i_StockTransDocH_Repository.GetByDocNumber(DocNum);

            if (StockTransHObject != null)
            {
                addStockTransViewModel = _mapper.Map<StockTransDocH, StockTransViewModel>(StockTransHObject);

                addStockTransViewModel.Lines = new List<StockTransLineViewModel>();
                addStockTransViewModel.NoteLines = new List<StockTransNoteViewModel>();

                foreach (var entry in StockTransHObject.StockTransDocLs.OrderBy(x => x.LineNum))
                {
                    StockTransLineViewModel dOLine = new StockTransLineViewModel();
                    dOLine = _mapper.Map<StockTransDocLs, StockTransLineViewModel>(entry);
                    addStockTransViewModel.Lines.Add(dOLine);
                }
                if (StockTransHObject.StockTransDocNotes != null)
                {
                    foreach (var entry in StockTransHObject.StockTransDocNotes.OrderBy(x => x.LineNum))
                    {
                        StockTransNoteViewModel dONoteLine = new StockTransNoteViewModel();
                        dONoteLine = _mapper.Map<StockTransDocNotes, StockTransNoteViewModel>(entry);
                        addStockTransViewModel.NoteLines.Add(dONoteLine);
                    }
                }
                addStockTransViewModel.DocDate = StockTransHObject.DocDate.ToString("dd'/'MM'/'yyyy");


            }
            else
            {
                TempData["GlobalErrMsg"] = "Sales quotation not found";
                return RedirectToAction("Index");
            }

            return View("Add", addStockTransViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken()]
        [AjaxOnly]
        [EditAuthorize(Roles = "Stock Transfer-Edit")]
        public JsonResult Add(StockTransViewModel StockTransObj)
        {
            IEnumerable<string> ModelErrList = Enumerable.Empty<string>();
            List<string> ErrList = new List<string>();
            if (StockTransObj.Lines == null || StockTransObj.Lines.Count() <= 0)
            {
                ErrList.Add("No lines added");

            }
            for (int i = 0; i < StockTransObj.Lines.Count(); i++)
            {
                decimal LocalAvailableQty = 0;
                LocalAvailableQty = i_DODocH_Repository.GetTotalSystemStockBalanceByItemCodeNew(StockTransObj.Lines[i].ItemCode, StockTransObj.Lines[i].FromLocation);
                IEnumerable<OITW> ItemStockDetails = i_OITW_Repository.GetLocationStockDetails(StockTransObj.Lines[i].ItemCode);
                string IsInventoryItem = ItemStockDetails.Select(x => x.Item.InvntItem).FirstOrDefault();
                if (IsInventoryItem.Equals("Y"))
                {
                    decimal SAPAvailableQty = ItemStockDetails.Where(x => x.WhsCode.Equals(StockTransObj.Lines[i].FromLocation)).Sum(x => (decimal?)(x.OnHand - x.IsCommited)) ?? 0;

                    decimal OrderItemQty = StockTransObj.Lines.Where(x => x.ItemCode.Equals(StockTransObj.Lines[i].ItemCode) && x.FromLocation.Equals(StockTransObj.Lines[i].FromLocation)).Sum(x => x.Qty);
                    decimal TotalAvailableQty = (LocalAvailableQty + SAPAvailableQty);
                    if (TotalAvailableQty < OrderItemQty)
                    {
                        ErrList.Add("Item " + StockTransObj.Lines[i].ItemCode + " not have enought stock in " + StockTransObj.Lines[i].FromLocationText + " warehouse in line no " + (i + 1));
                    }
                }
            }
            if (ModelState.IsValid && ErrList.Count() <= 0)
            {
                if (StockTransObj.DocNum.Equals("New"))
                {
                    StockTransDocH StockTransHeader = new StockTransDocH();
                    StockTransHeader = _mapper.Map<StockTransViewModel, StockTransDocH>(StockTransObj);

                    List<StockTransDocLs> Lines = _mapper.Map<List<StockTransLineViewModel>, List<StockTransDocLs>>(StockTransObj.Lines);
                    List<StockTransDocNotes> NoteLines = _mapper.Map<List<StockTransNoteViewModel>, List<StockTransDocNotes>>(StockTransObj.NoteLines);
                    StockTransHeader.CreatedBy = User.Identity.Name;
                    StockTransHeader.Status = (short)DocumentStatuses.Open;
                    if (StockTransObj.SubmittedToSAP == true)
                    {
                        StockTransHeader.SyncStatus = (short)SyncStatuses.Waiting_For_Syncing;
                    }
                    string ValidationMessage = string.Empty;
                    string STDocNum = string.Empty;
                    if (!i_StockTransDocH_Repository.AddStockTrans(StockTransHeader, Lines, NoteLines,ref ValidationMessage, ref STDocNum))
                    {
                        ErrList.Add(ValidationMessage);
                    }
                    else
                    {
                        StockTransObj.DocNum = STDocNum;
                        StockTransObj.DocEntry = long.Parse(ValidationMessage);
                    }
                }
                else
                {
                    StockTransDocH StockTransHeader = i_StockTransDocH_Repository.GetByDocNumber(StockTransObj.DocNum);

                    if (StockTransHeader != null)
                    {

                        if (StockTransObj.SubmittedToSAP == true && !User.IsInRole("Submit To SAP"))
                        {
                            ErrList.Add("Access denied");
                        }
                        else if (CannotPrintAndSave(StockTransHeader.DocEntry.ToString()))
                        {
                            ErrList.Add("Access denied");
                        }
                        else if(StockTransHeader.SubmittedToSAP == true)
                        {
                            ErrList.Add("This document already submitted to SAP");
                        }
                        else if (StockTransHeader.SyncedToSAP == true)
                        {
                            ErrList.Add("This document already synced to SAP");
                        }
                        else if (StockTransHeader.SyncStatus.Equals((short)SyncStatuses.Sync_Failed))
                        {
                            string ValidationMessage = string.Empty;
                            StockTransHeader.SyncStatus = (short)SyncStatuses.Waiting_For_Syncing;
                            if (!i_StockTransDocH_Repository.ResubmitStockTransToSAP(StockTransHeader, ref ValidationMessage))
                            {
                                ErrList.Add(ValidationMessage);
                            }
                        }
                        else
                        {
                            long DocEntry = StockTransHeader.DocEntry;
                            StockTransHeader = _mapper.Map<StockTransViewModel, StockTransDocH>(StockTransObj);

                            StockTransHeader.DocEntry = DocEntry;

                            List<StockTransDocLs> Lines = _mapper.Map<List<StockTransLineViewModel>, List<StockTransDocLs>>(StockTransObj.Lines);

BMSS.WebUI/Views/StockTrans/Index.cshtml
@using BMSS.Domain
@model IEnumerable<StockTransDocH>
@{
    ViewBag.Title = "List of Stock Transfer";
}
@section Styles {
    @Styles.Render("~/DataTablesCss")
}
@section Content_Header {
    <section class="content-header">
        <h1>
            Stock Transfer Listing
            <small>Stock Transfer</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href='@Url.Action("Index", "Home")'><i class="fa fa-dashboard"></i>Transactions</a></li>
            <li class="active">Stock Transfer</li>
        </ol>
    </section>
}
<div class="row">
    <div class="col-12">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">List of Stock Transfer</h3>
                <div class="box-tools" style="top: 3px;"><a class="btn btn-primary" href="@Url.Action("Add", "StockTrans")" role="button">Add</a></div>
            </div>
            <div class="box-body">
                <table id="DeliveryOrderList" class="table table-bordered table-striped responsive nowrap bmdatatable dblEdit" data-fixed-header="true" data-auto-width="true" data-paging="true" data-searching="true" data-length-change="true" data-page-length="100" data-ordering="true" style="width:100%">
                    <thead>
                        <tr>
                            <th>Doc #</th>
                            <th>Date</th>
                            <th>Period</th>
                            <th>Doc Status</th>
                            <th>Print Status</th>
                            <th>SAP Status</th>
                            <th>Ref</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var i in Model)
                        {
                            <tr  data-toggle="tooltip" title="double click to edit">
                                <td>
                                    @i.DocNum
                                    @using (Html.BeginForm("Edit", null, null, FormMethod.Get, new { id = "DetailForm" }))
                                    {
                                        @Html.Hidden("DocNum", @i.DocNum)
                                    }
                                </td>
                                <td>@i.DocDate.ToString("dd'/'MM'/'yyyy")</td>
                                <td>@i.DocDate.ToString("MM'/'yyyy")</td>
                                <td>@Html.GetDocStatusName(i.Status)</td>
                                <td>@Html.GetPrintedStatusName(i.PrintedStatus)</td>
                                <td>
                                    @Html.GetSyncStatusName(i.SyncStatus)
                                    @if (i.SyncStatus > 1)
                                    {
                                        <span data-toggle='popover' data-trigger='hover' data-placement='right' data-html='true' data-content='@i.SyncRemarks' data-title='Sync Remarks'><i class='fa fa-fw fa-info-circle'></i></span>
                                    }
                                </td>
                                <td>@i.Ref</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/DataTables")
    @Scripts.Render("~/Own")
}